add support for ch-elm testing
ahdis/matchbox-int-tests pull request #9
Opened 2024-04-08 08:55 UTC by oliveregger

needed however to deactivate ch-emed testing due to #7, better to fix that issue first, that we can do the integration tests with the interrnal terminology server.

2024-04-08 14:04 UTC, qligier requested changes

2024-04-08 14:04 UTC, qligier commented on pom.xml
> +        <java.version>21</java.version>
No need to bump the Java version here, it's the syntax level, not the JDK/JRE that will be used.
In Matchbox, the runner uses the JRE 20, so it will fail: https://github.com/ahdis/matchbox/blob/main/.github/workflows/integration_tests.yml

2024-04-08 14:20 UTC, oliveregger commented on pom.xml
> +        <java.version>21</java.version>
could we not use 21 in matchbox? 21 is LTS

2024-04-08 14:28 UTC, qligier commented on pom.xml
> +        <java.version>21</java.version>
Indeed, we should move to Java 21 LTS. Most of our uses are Java 20, probably because it was the last version when everything was set up.

2024-04-09 08:16 UTC, qligier approved these changes

2024-04-09 09:20 UTC, merged